version: '3'

services:

  musicstore:
    image: musicstore:1.0
    build:
      context: ./UI
      dockerfile: Dockerfile
    environment:
      - "ApiGateway=http://apigateway.api:8084"
    depends_on:
      - apigateway.api

  apigateway.api:
    image: gateway:1.0
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    environment:
      - "Catalog=http://catalog.api:8082"
      - "Basket=http://basket.api:8083"
      - "Ordering=http://ordering.api:8085"

  catalog.api:
    image: catalog:1.0
    build:
      context: ./Catalog.Service
      dockerfile: Dockerfile
    environment:
      - CatalogConnectionString=
      - ServiceBusPublisherConnectionString=

  basket.api:
    image: basket:1.0
    build:
      context: ./Basket.Service
      dockerfile: Dockerfile
    depends_on:
      - catalog.api
    environment:
      - "Catalog=http://catalog.api:8082"
      - StorageAccount=
      - StorageKey=
      - ServiceBusPublisherConnectionString=

  ordering.api:
    image: ordering:1.0
    build:
      context: ./Ordering.Service
      dockerfile: Dockerfile
    environment:
      - CosmosEndpoint=
      - CosmosPrimaryKey=
      - ServiceBusPublisherConnectionString=
