apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      component: catalog
  template:
    metadata:
      labels:
        app: musicstore
        component: catalog
    spec:
      containers:
      - name: catalog
        image: 
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: CatalogConnectionString
          value: 
        - name: ServiceBusPublisherConnectionString
          value: 
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket
spec:
  replicas: 1
  selector:
    matchLabels:
      component: basket
  template:
    metadata:
      labels:
        app: musicstore
        component: basket
    spec:
      containers:
      - name: basket
        image: 
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: StorageAccount
          value: 
        - name: StorageKey
          value: 
        - name: catalog
          value: http://catalog
        - name: ServiceBusPublisherConnectionString
          value: 
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      component: gateway
  template:
    metadata:
      labels:
        app: musicstore
        component: gateway
    spec:
      containers:
      - name: gateway
        image: 
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: Catalog
          value: http://catalog
        - name: Basket
          value: http://basket
        - name: Ordering
          value: http://ordering
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ordering
  template:
    metadata:
      labels:
        app: musicstore
        component: ordering
    spec:
      containers:
      - name: ordering
        image: 
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: CosmosEndpoint
          value: 
        - name: CosmosPrimaryKey
          value: 
        - name: ServiceBusPublisherConnectionString
          value: 
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ui
  template:
    metadata:
      labels:
        app: musicstore
        component: ui
    spec:
      containers:
      - name: ui
        image: 
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: ApiGateway
          value: http://gateway
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: musicstore
  name: basket
spec:
  ports:
  - port: 80
  selector:
    app: musicstore
    component: basket
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: musicstore
  name: catalog
spec:
  ports:
  - port: 80
  selector:
    app: musicstore
    component: catalog
  type: LoadBalancer  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: musicstore
  name: gateway
spec:
  ports:
  - port: 80
  selector:
    app: musicstore
    component: gateway
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: musicstore
  name: ordering
spec:
  ports:
  - port: 80
  selector:
    app: musicstore
    component: ordering
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: musicstore
  name: ui
spec:
  ports:
  - port: 80
  selector:
    app: musicstore
    component: ui
  type: LoadBalancer
---
